import type { CSSProperties } from 'react';

// Inline product-detail panel (NOT an overlay). Rendered in the widget's normal
// flow so it can't be clipped/hidden by the custom element's shadow DOM,
// transformed wrappers, or the preview iframe sandbox.
export const styles = {
  panel: {
    width: '100%',
    boxSizing: 'border-box',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif',
  } as CSSProperties,
  back: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    margin: '0 0 12px',
    padding: '6px 4px',
    border: 'none',
    background: 'transparent',
    color: '#116dff',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
  } as CSSProperties,
  backArrow: {
    fontSize: '20px',
    lineHeight: 1,
  } as CSSProperties,
  card: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '20px',
    alignItems: 'flex-start',
    padding: '16px',
    background: '#ffffff',
    border: '1px solid #e5e5e5',
    borderRadius: '16px',
    boxSizing: 'border-box',
  } as CSSProperties,
  imageWrap: {
    flex: '1 1 240px',
    maxWidth: '360px',
    aspectRatio: '1 / 1',
    background: '#f3f3f3',
    borderRadius: '12px',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  } as CSSProperties,
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
    display: 'block',
  } as CSSProperties,
  body: {
    flex: '1 1 220px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    paddingTop: '8px',
  } as CSSProperties,
  name: {
    margin: 0,
    fontSize: '22px',
    fontWeight: 600,
    color: '#2b2b2b',
  } as CSSProperties,
  price: {
    margin: 0,
    fontSize: '18px',
    fontWeight: 500,
    color: '#555555',
  } as CSSProperties,
  description: {
    margin: '2px 0 0',
    fontSize: '14px',
    lineHeight: 1.5,
    color: '#444444',
    whiteSpace: 'pre-wrap',
  } as CSSProperties,
  button: {
    alignSelf: 'flex-start',
    marginTop: '8px',
    padding: '12px 22px',
    border: 'none',
    borderRadius: '24px',
    background: '#116dff',
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: 600,
    cursor: 'pointer',
  } as CSSProperties,
  note: {
    margin: '4px 0 0',
    fontSize: '13px',
    color: '#999999',
  } as CSSProperties,
} as const;
